src/main/java/com/kenfogel/quizbeans/ProblemBean.java
package com.kenfogel.quizbeans;

import java.io.Serializable;
import java.util.ArrayList;

/**
 * This is an ordinary bean that will be instantiated by the CDI managed QuizBean.
 * 
 * @author Ken
 * @version 1.0
 *
 */
public class ProblemBean implements Serializable {

	private static final long serialVersionUID = -8263450944127228631L;

	private ArrayList<Integer> sequence;
	private int solution;

	public ProblemBean(int[] values, int solution) {
		sequence = new ArrayList<>();
		for (int i = 0; i < values.length; i++) {
			sequence.add(values[i]);
		}
		this.solution = solution;
	}

	public ArrayList<Integer> getSequence() {
		return sequence;
	}

	public void setSequence(ArrayList<Integer> newValue) {
		sequence = newValue;
	}

	public int getSolution() {
		return solution;
	}

	public void setSolution(int newValue) {
		solution = newValue;
	}
}

src/main/java/com/kenfogel/quizbeans/QuizBean.java
package com.kenfogel.quizbeans;

import java.io.Serializable;
import java.util.ArrayList;

import javax.inject.Named;
import javax.enterprise.context.SessionScoped;

/**
 * This is a CDI managed data bean whose methods are actually doing business
 * processing. This is not the best practices but it does help us understand a
 * little more about these beans. In the end we will use action beans for
 * business processes.
 *
 * @author Ken
 * @version 1.0
 *
 */
@Named
@SessionScoped
public class QuizBean implements Serializable {

    private static final long serialVersionUID = -5696075206135950369L;

    private ArrayList<ProblemBean> problems = new ArrayList<>();
    private int currentIndex;
    private int score;

    /**
     * Each problem is a sequence of numbers. The user must guess what the next
     * number in the sequence is
     */
    public QuizBean() {
        System.out.println("QuizBean Constructor");
        problems.add(
                new ProblemBean(new int[]{3, 1, 4, 1, 5}, 9)); // pi
        problems.add(
                new ProblemBean(new int[]{1, 1, 2, 3, 5}, 8)); // fibonacci
        problems.add(
                new ProblemBean(new int[]{1, 4, 9, 16, 25}, 36)); // squares
        problems.add(
                new ProblemBean(new int[]{2, 3, 5, 7, 11}, 13)); // primes
        problems.add(
                new ProblemBean(new int[]{1, 2, 4, 8, 16}, 32)); // powers of 2
    }

    public void setProblems(ArrayList<ProblemBean> newValue) {
        problems = newValue;
        currentIndex = 0;
        score = 0;
    }

    public int getScore() {
        return score;
    }

    public ProblemBean getCurrent() {
        return problems.get(currentIndex);
    }

    public String getAnswer() {
        return "";
    }

    public void setAnswer(String newValue) {
        try {
            int answer = Integer.parseInt(newValue.trim());
            if (getCurrent().getSolution() == answer) {
                score++;
            }
            currentIndex = (currentIndex + 1) % problems.size();
        } catch (NumberFormatException ex) {
            System.out.println("Error converting string to a value\n" + ex.getMessage());
        }
    }
}

src/main/webapp/index.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>#{msgs.title}</title>
    </h:head>
    <h:body>
        <h:form>
            <h3>#{msgs.heading}</h3>
            <p>
                <!-- The string in the bundle has a placeholder that will be
                     filled with the f:param value
                -->
                <h:outputFormat value="#{msgs.currentScore}">
                    <f:param value="#{quizBean.score}"/>
                </h:outputFormat>
            </p>
            <p>#{msgs.guessNext}</p>
            <p>#{quizBean.current.sequence}</p>
            <p>
                #{msgs.answer}
                <h:inputText value="#{quizBean.answer}"/>
            </p>
            <!-- Without a navigation rule this commandButton just reloads
                 the current page
            -->
            <p><h:commandButton value="#{msgs.next}"/></p>
        </h:form>
    </h:body>
</html>